"""Invoice rendering — produces a viewable HTML document.

Production swaps in WeasyPrint or a HTML→PDF microservice. Same interface:
input dict, output bytes + mime + extension.
"""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Any


def _money(v: Any) -> str:
    return f"{Decimal(str(v)):,.0f}".replace(",", " ")


def render_invoice(invoice: dict[str, Any], *, company: dict[str, Any], client: dict[str, Any] | None) -> tuple[bytes, str, str]:
    items_html = "".join(
        f"<tr><td>{i['name']}</td><td class='r'>{i['qty']}</td>"
        f"<td class='r'>{_money(i['price'])}</td>"
        f"<td class='r'>{_money(Decimal(str(i['qty'])) * Decimal(str(i['price'])))}</td></tr>"
        for i in invoice["items"]
    )
    client_block = (
        f"<div><b>Bill to</b><br/>{client['name']}<br/>"
        f"BIN {client.get('bin') or '—'}<br/>{client.get('phone') or ''}</div>"
        if client else "<div><b>Bill to</b><br/>—</div>"
    )
    html = f"""<!doctype html>
<html><head><meta charset="utf-8"/><title>Invoice {invoice['number']}</title>
<style>
  body {{ font: 14px/1.5 -apple-system, system-ui, sans-serif; color:#111; max-width:760px; margin:32px auto; padding:0 24px; }}
  h1 {{ font-size:22px; margin:0 0 4px; }}
  .muted {{ color:#666; }}
  .row {{ display:flex; justify-content:space-between; margin:24px 0; }}
  table {{ width:100%; border-collapse:collapse; margin-top:16px; }}
  th, td {{ border-bottom:1px solid #e5e7eb; padding:8px 6px; text-align:left; }}
  th {{ font-size:11px; text-transform:uppercase; color:#6b7280; letter-spacing:.04em; }}
  td.r, th.r {{ text-align:right; font-variant-numeric: tabular-nums; }}
  .totals {{ margin-top:16px; margin-left:auto; width:280px; }}
  .totals div {{ display:flex; justify-content:space-between; padding:4px 0; }}
  .totals .grand {{ border-top:2px solid #111; margin-top:6px; padding-top:8px; font-weight:600; }}
</style></head><body>
  <h1>Invoice {invoice['number']}</h1>
  <div class="muted">Issued {invoice['issue_date']} · Due {invoice.get('due_date') or '—'}</div>
  <div class="row">
    <div><b>From</b><br/>{company['name']}<br/>BIN {company.get('bin') or '—'}</div>
    {client_block}
  </div>
  <table>
    <thead><tr><th>Item</th><th class="r">Qty</th><th class="r">Price</th><th class="r">Total</th></tr></thead>
    <tbody>{items_html}</tbody>
  </table>
  <div class="totals">
    <div><span>Subtotal</span><span>{_money(invoice['subtotal'])} {invoice['currency']}</span></div>
    <div><span>Tax</span><span>{_money(invoice['tax_total'])} {invoice['currency']}</span></div>
    <div class="grand"><span>Total</span><span>{_money(invoice['total'])} {invoice['currency']}</span></div>
  </div>
  <p class="muted" style="margin-top:32px">Generated by Buchuchet · {datetime.utcnow().isoformat(timespec='seconds')}Z</p>
</body></html>"""
    return html.encode("utf-8"), "text/html", "html"
